version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  make-pull-request:
    docker:
      - image: cimg/base:2022.06
    steps:
      - run:
          name: Trigger e2e test pipeline 
          command: |
              curl --request POST \
                --url https://circleci.com/api/v2/project/gh/0rqheus/todo-app-client/pipeline \
                --header "Circle-Token: $GITHUB_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch":"main","parameters":{"image-name":"'$DOCKER_LOGIN"/"$CIRCLE_PROJECT_REPONAME":"0.1.<< pipeline.number >>'"}}'

workflows:
  sample:
    jobs:
      - make-pull-request:
          context: Secrets
