name: Integration test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pull-and-run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 0rqheus/todo-app-client
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Use Node.js '16.x'
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - run: npm ci

    - run: npm test
      env:
        REACT_APP_HOST: ${{ secrets.BACKEND_HOST }}
